apiVersion: v1
kind: Service
metadata:
  labels:
    app: miles-ji-pipeline-from-scratch
    app.kubernetes.io/instance: miles-ji-pipeline-from-scratch
    app.kubernetes.io/name: squad5-pipeline-from-scratch
  name: recorder
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8088
  selector:
    app: miles-ji-pipeline-from-scratch
    app.kubernetes.io/instance: miles-ji-pipeline-from-scratch
    app.kubernetes.io/name: squad5-pipeline-from-scratch
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: miles-ji-pipeline-from-scratch
    app.kubernetes.io/instance: miles-ji-pipeline-from-scratch
    app.kubernetes.io/name: squad5-pipeline-from-scratch
  name: recorder
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: miles-ji-pipeline-from-scratch
      app.kubernetes.io/instance: miles-ji-pipeline-from-scratch
      app.kubernetes.io/name: squad5-pipeline-from-scratch
  template:
    metadata:
      labels:
        app: miles-ji-pipeline-from-scratch
        app.kubernetes.io/instance: miles-ji-pipeline-from-scratch
        app.kubernetes.io/name: squad5-pipeline-from-scratch
    spec:
      containers:
      - image: quay.io/min_ji_gz_ibm/cloudnative:07335635504c7437b29482e8e87fac47df2ab567
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8088
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: recorder
        ports:
        - containerPort: 8088
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: miles-ji-pipeline-from-scratch
    app.kubernetes.io/instance: miles-ji-pipeline-from-scratch
    app.kubernetes.io/name: squad5-pipeline-from-scratch
  name: recorder
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: recorder
    weight: 100
  wildcardPolicy: None
