apiVersion: v1
kind: Service
metadata:
  labels:
    app: miles-ji-pipeline-from-scratch
    app.kubernetes.io/instance: miles-ji-pipeline-from-scratch
    app.kubernetes.io/name: squad5-pipeline-from-scratch
  name: caller
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: miles-ji-pipeline-from-scratch
    app.kubernetes.io/instance: miles-ji-pipeline-from-scratch
    app.kubernetes.io/name: squad5-pipeline-from-scratch
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: miles-ji-pipeline-from-scratch
    app.kubernetes.io/instance: miles-ji-pipeline-from-scratch
    app.kubernetes.io/name: squad5-pipeline-from-scratch
  name: caller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miles-ji-pipeline-from-scratch
      app.kubernetes.io/instance: miles-ji-pipeline-from-scratch
      app.kubernetes.io/name: squad5-pipeline-from-scratch
  template:
    metadata:
      labels:
        app: miles-ji-pipeline-from-scratch
        app.kubernetes.io/instance: miles-ji-pipeline-from-scratch
        app.kubernetes.io/name: squad5-pipeline-from-scratch
    spec:
      containers:
      - image: quay.io/min_ji_gz_ibm/cloudnative:b4adfb6de0fae958889490abc4e086eea927d948
        imagePullPolicy: Always
        name: caller
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: miles-ji-pipeline-from-scratch
    app.kubernetes.io/instance: miles-ji-pipeline-from-scratch
    app.kubernetes.io/name: squad5-pipeline-from-scratch
  name: caller
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: caller
    weight: 100
  wildcardPolicy: None
